### ISSUE TITLE
When mounting a CIFS volume, the service does not get replicated

### ISSUE THREAD

**Issue by GasimGasimzada** [trajano/docker-volume-plugins#22]
In this case, nothing works. No logs or anything.

Running the following w/ cifs-utils on host machine works (CentOS 7):

```bash
 mount -t cifs   -o vers=3.02,mfsymlinks,file_mode=0666,dir_mode=0777,credentials=/opt/apps/photos/secret.txt //photobank/photos /opt/apps/photos/testcifs
```

However, when using the plugin the service just gets stuck. No replication, no logs. Nothing is happening:

```yml
version: '3.7'
services:
  image: emby/embyserver
    networks:
      - public-net
    volumes:
      - type: volume
        source: emby-config
        target: /config
      - photobank:/mnt/photobank
    secrets:
      - source: photobank.credentials
        target: /root/credentials/photobank@photos
    deploy:
       ... deploy options here
secrets:
  photobank.credentials:
    external: true
networks:
  public-net:
    external: true
volumes:
  emby-config:
  photobank:
    driver: trajano/cifs-volume-plugin
    driver_opts:
      cifsopts: vers=3.02,mfsymlinks,file_mode=0666,dir_mode=0777
    name: "photobank/photos"
```

(photobank.credentials secret stores contents of "secret.txt," which is used by the bash command above.

Using normal volumes work. However, using the plugin volume does nothing. It is just stuck.

Docker version:

```bash
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:58:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:56:46 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

What am I doing wrong here?
