### ISSUE TITLE
Subdir is not created and therefore doesn't seem to work, need to create subdir first

### ISSUE THREAD

**Issue by iangregsondev** [trajano/docker-volume-plugins#31]
Hi,

I wonder if there is a fix coming or could we update the readme about a potential bug?

I had a container setup to work via gluster i.e.

```
volumes:
  registry_data:
    driver: glusterfs
    name: "gfs/docker-registry"
```

The container started and everything appeared to be working but the disks were not getting the updates. So i brought down my stack and created the directory manually i.e.

```
mkdir docker-regsitry
``` 

on one of the gluster nodes and now all is working again after brining the stack back up

I see the files appearing on the disk.

Thanks.
