### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by autoize** [trajano/docker-volume-plugins#32]
**Versions**
* glusterfs 3.13.2 on Ubuntu 18.04
* Docker version 19.03.7, build 7141c199a2
* glusterfs:latest "GlusterFS plugin for Docker"

**Hosts**
**Gluster hosts** 10.131.52.75,10.131.54.189,10.131.55.104
**Docker Swarm hosts** 10.131.121.134,10.131.121.220,10.131.119.235

`gluster volume set gfs auth.allow 10.131.52.75,10.131.54.189,10.131.55.104,10.131.121.134,10.131.121.220,10.131.119.235` has been set on Gluster volume

UFW firewall rules are set as follows on all Gluster hosts.
All traffic from the LAN is allowed. 

```
22/tcp                     ALLOW       Anywhere
Anywhere                   ALLOW       10.131.52.75
Anywhere                   ALLOW       10.131.54.189
Anywhere                   ALLOW       10.131.55.104
Anywhere                   ALLOW       10.131.121.134
Anywhere                   ALLOW       10.131.121.220
Anywhere                   ALLOW       10.131.119.235
Anywhere                   ALLOW       10.131.52.75/udp
Anywhere                   ALLOW       10.131.54.189/udp
Anywhere                   ALLOW       10.131.55.104/udp
Anywhere                   ALLOW       10.131.121.134/udp
Anywhere                   ALLOW       10.131.121.220/udp
Anywhere                   ALLOW       10.131.119.235/udp
22/tcp (v6)                ALLOW       Anywhere (v6)
```

When deploying the below Docker stack, the following error is encountered
```
wbhn2xvfpm79bd7615sa6pt7v   test_foo.1          alpine:latest@sha256:ab00606a42621fb68f2ed6ad3c88be54397f981a7b70a79db3d1172b11c4367d   docker1             Ready               Rejected 1 second ago     "open /var/lib/docker/plugins/31ec62ae30657bcbaadf9435f2731b72610eb81d3c3c3276e1a9632a86fd351f/propagated-mount/f7eca8725e52c250df3cb88a102c04bee71f95b8f99aa1cfc778eb43e2b67b75: transport endpoint is not connected"
648vue9e87dmhsl5lfor1bqn0    \_ test_foo.1      alpine:latest@sha256:ab00606a42621fb68f2ed6ad3c88be54397f981a7b70a79db3d1172b11c4367d   docker2             Shutdown            Rejected 5 seconds ago    "open /var/lib/docker/plugins/c46bd9fc2f5d9980398d594289fca4fc535f057d8ae7fe069e4381416cc940a8/propagated-mount/e1077d958f3233f0de63efabc218c14477c00090615b71320c9895dc0b3c7f06: transport endpoint is not connected"
```

```
version: "3.4"

services:
  foo:
    image: alpine
    command: ping localhost
    networks:
      - net
    volumes:
      - vol1:/tmp

networks:
  net:
    driver: overlay

volumes:
  vol1:
    driver: glusterfs
    driver_opts:
      servers: 10.131.52.75,10.131.54.189,10.131.55.104
    name: "gfs/vol1"
```

The **vol1** subdirectory has already been created on the Gluster volume. The managed plugin has been installed and enabled on all 3 Swarm hosts, and the IPs of the Gluster hosts have also been set. 

Excerpt from `docker plugin inspect glusterfs:latest`

```
            "Env": [
                "SERVERS=10.131.52.75,10.131.54.189,10.131.55.104"
            ],
```

Any help would be appreciated. Thanks in advance!
