### ISSUE TITLE
name Additional property name is not allowed

### ISSUE THREAD

**Issue by Serhiy-Nazarov** [trajano/docker-volume-plugins#34]
In my `docker-compose.yml` I have:
```
volumes:
  vol1:
    driver: glusterfs
    name: "gfs"
```
I'm using docker swarm.
`docker stack deploy -c docker-compose.yml vol1-demo`
I have error:
`name Additional property name is not allowed`

Anybody can help me?
