### ISSUE TITLE
Cannot mount CIFS shares: permission denied

### ISSUE THREAD

**Issue by paulhutchings** [trajano/docker-volume-plugins#37]
I have an Ubuntu machine with Docker and a NAS I'm trying to use for the storage - in this case Plex. Here is my `docker-compse.yml`:

```
version: '3.4'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - '32400:32400/tcp'
      - '32469:32469/tcp'
      - '1900:1900/udp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    environment:
      - TZ=America/New_York
      - PLEX_CLAIM=$PLEX_CLAIM
    volumes:
      - 'plex_config:/config'
      - 'plex_media:/media'
    tmpfs: /transcode

volumes:
   plex_config:
   plex_media:
      driver: cifs
      name: "192.168.2.9/media"

```
I have a credentials file for the share placed on the docker host at `/root/credentials/192.168.2.9@media` that looks like this:
```
username=plex
password=<password>
domain=WORKGROUP # I don't use a domain, so I assume this is what to use? or can it just be left blank in this case?
```
However, when I run `docker-compose up` I get the following error:
```
ERROR: for plex  Cannot start service plex: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/docker/5000.5000/plugins/39cedb6cd9c9cbdc785ce4340bc31a0d85bba919fb5add30a08bf3bd8ab6b80f/propagated-mount/cd368dad7818f77a4c07bf22e59898a62eaa293416b03897cb6491aaa7579393\\\" to rootfs \\\"/var/lib/docker/5000.5000/overlay2/51889ee2bcb56a491ad370b245b871799bac66fa390b4443ad7cd7ab33e86e9b/merged\\\" at \\\"/media\\\" caused \\\"stat /var/lib/docker/5000.5000/plugins/39cedb6cd9c9cbdc785ce4340bc31a0d85bba919fb5add30a08bf3bd8ab6b80f/propagated-mount/cd368dad7818f77a4c07bf22e59898a62eaa293416b03897cb6491aaa7579393: permission denied\\\"\"": unknown
ERROR: Encountered errors while bringing up the project.
```
I can confirm that the credentials in the file have appropriate permissions as I tested logging into the share on my Windows laptop with them and can read/write/etc. I am using namespace remapping with the user `container` with `uid` and `gid` of 5000 as seen in the error message.

Could anyone possibly help me out with this?
